### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by gBasil** [mon/SyncLoop#1]
Is there an open source license for SyncLoop or can we not (legally) use it?

**Comment by wopian** [comment]
The MIT license is embedded in the source files:

- https://github.com/mon/SyncLoop/blob/master/js/SoundManager.js#L1-L20
- https://github.com/mon/SyncLoop/blob/master/js/SyncLoop.js#L1-L20

**Comment by mon** [comment]
To be 100% clear - wopian is correct! You can do whatever you want with the source (even commercially), as long as you include a copy of the license.

Not a part of the license, but - I would like to know if you are using it for something interesting!

**Comment by mon** [comment]
I also added a LICENSE file for clarity

**Comment by gBasil** [comment]
> The MIT license is embedded in the source files

Ah, my bad! I completely forgot the licenses were in the files, I should've double checked. Thanks for the clarification.

**Comment by gBasil** [comment]
> I would like to know if you are using it for something interesting!

I threw together a little React component for a small SyncLoop player.

![gif](https://user-images.githubusercontent.com/57513430/142709723-cbd81683-f510-41e5-8428-260a402b7c91.gif)

**Comment by mon** [comment]
That's super cool! I should really get into React, looks awesome.

**Comment by GunnerBasil** [comment]
Thank you! I started out with React about four-ish ago with Next.js, so I'm pretty new to the framework. It's a lot different from vanilla JS, which is what I usually use.
