### ISSUE TITLE
Firefox v104 doesn't play the loops

### ISSUE THREAD

**Issue by maltherd** [mon/SyncLoop#2]
Hi!

Thanks for your work. It is appreciated :)

My Firefox v104 (Arch Linux) doesn't play the loops on [your site](https://loop.mon.im/working.html). 
It loads up to 100% and then nothing.

The console shows this:
`An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page.`

I trust there is an easy way to fix this. 
I see it's an old project, but I thought to let you know anyway, just in case.

Thanks again and have a good one!

**Comment by mon** [comment]
It's been bothering me for a while, since Chrome doesn't really like it either. I need to add a quick "click to start" button.
Since one other person (you!) is now bothered, I'll try to fix it in a few days

**Comment by mon** [comment]
Fixed in 98aeac39845291a9a17052cd90196cef53ebf1ee, thanks for the bump.
